### ISSUE TITLE
Dock

### ISSUE THREAD

**Issue by codic12** [jEsuSdA/the-perfect-desktop#1]
What dock do you use? Config files?

**Comment by jEsuSdA** [comment]
I use a simpe XFCE Panel.
But it is full of Launchers. ;)

Sending you some screenshots about the configuration:
![imagen](https://user-images.githubusercontent.com/5833446/66817561-318e5b00-ef3c-11e9-8b4c-411543837c8a.png)


![imagen](https://user-images.githubusercontent.com/5833446/66817578-3b17c300-ef3c-11e9-9d93-e25a5827c01d.png)

For the background image, you should use 
https://github.com/jEsuSdA/the-perfect-desktop/blob/master/greybird-patched/panel-bg3.png


![imagen](https://user-images.githubusercontent.com/5833446/66817604-44a12b00-ef3c-11e9-9d9e-5109d2b81536.png)


I hope this helps you.
Thanks a lot for your message. ;)

**Comment by codic12** [comment]
Ok, thanks. Can you try my great material theme? https://codeberg.org/gsbhasin84/Materiav2/src/branch/master/README.md

**Comment by jEsuSdA** [comment]
@gsbhasin123 nice work!

I tried your themes, but I don't feel comfortable using too dark or too light themes cause I spend a lot of hours working with computers and neutral colors are more relaxing to me.

In addition to that, as I am graphical designer and spend a lot of time retouching images and creating graphics, too dark and too light themes (or themes with pure colors) affects my color perception, so I prefer gray themes (like Greybird).

I know... I'm very picky... hahahaha. 

Thanks a lot!!

**Comment by codic12** [comment]
@jEsuSdA Actually, thanks for the idea! I'm going to make a version of my theme with the Greybird colorscheme. If so, can you try it again?

**Comment by codic12** [comment]
@jEsuSdA done! https://codeberg.org/gsbhasin84/Materiav2/src/branch/master/README.md Scroll down to the bottom

**Comment by codic12** [comment]
Also it would be great if you could add your dock config to the README

**Comment by jEsuSdA** [comment]
@gsbhasin123 Wow! Thanks!
But there is no theme files, only screenshot. ;)

**Comment by codic12** [comment]
@jEsuSdA It is there, but in the `light` section. https://codeberg.org/gsbhasin84/Materiav2/src/branch/master/light/greybird

**Comment by codic12** [comment]
I don't get what you mean!

**Comment by jEsuSdA** [comment]
@gsbhasin123 Thank you! I see. ;)
Thanks a lot!
